use std::path::Path;

use clap::{Args, ValueEnum};
use serde_json::Value;

/// Print the checked-in generated files (used by `just gen`).
#[derive(Debug, Args)]
pub(crate) struct GenDocs {
    /// Which document to print to stdout
    #[arg(value_enum)]
    target: Target,
}

#[derive(Debug, Clone, Copy, ValueEnum)]
enum Target {
    /// The CLI reference, from the clap definitions
    Cli,
    /// The config.toml reference, from the config JSON schema
    Config,
    /// The config JSON schema itself (devconcurrent.schema.json)
    Schema,
}

impl GenDocs {
    pub(crate) fn run(self) -> eyre::Result<()> {
        match self.target {
            Target::Cli => print_markdown(&cli_markdown()),
            Target::Config => print_markdown(&config_markdown()?),
            Target::Schema => println!("{}", schema_json()?),
        }
        Ok(())
    }
}

fn print_markdown(body: &str) {
    println!("<!-- Generated by `devconcurrent gen-docs`. Do not edit; run `just gen`. -->");
    println!();
    print!("{body}");
}

/// The schema for config.toml, as checked in at `devconcurrent.schema.json`.
///
/// `x-tombi-toml-version` records the TOML spec version our `toml` dependency
/// implements, so editors don't suggest syntax we can't parse. Reading
/// Cargo.lock means this target only works from a checkout, which is fine:
/// it's only ever run via `just gen`.
fn schema_json() -> eyre::Result<String> {
    let workspace_root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .ok_or_else(|| eyre::eyre!("cli crate lives at <workspace>/crates/cli"))?;
    let cargo_lock_path = workspace_root.join("Cargo.lock");
    let cargo_lock = std::fs::read_to_string(&cargo_lock_path)
        .map_err(|e| eyre::eyre!("read {}: {e}", cargo_lock_path.display()))?;
    let toml_spec_version = toml_spec_version(&cargo_lock)?;

    let mut schema = crate::schema();
    schema.ensure_object().insert(
        "x-tombi-toml-version".into(),
        format!("v{toml_spec_version}").into(),
    );
    Ok(serde_json::to_string_pretty(&schema)?)
}

/// Extract the TOML spec version from the `toml` crate's build metadata in
/// Cargo.lock. The crate is versioned as e.g. `1.1.2+spec-1.1.0`, where the
/// part after `+spec-` is the TOML specification version it conforms to.
fn toml_spec_version(cargo_lock: &str) -> eyre::Result<String> {
    let mut lines = cargo_lock.lines();
    while let Some(line) = lines.next() {
        if line != r#"name = "toml""# {
            continue;
        }
        let Some(version_line) = lines.next() else {
            continue;
        };
        let version = version_line
            .strip_prefix(r#"version = ""#)
            .and_then(|s| s.strip_suffix('"'));
        let Some(version) = version else { continue };
        if let Some((_, spec)) = version.split_once("+spec-") {
            return Ok(spec.to_string());
        }
    }
    eyre::bail!("no `toml` package with `+spec-` build metadata in Cargo.lock")
}

fn cli_markdown() -> String {
    let options = clap_markdown::MarkdownOptions::new()
        .title("CLI".to_string())
        .show_footer(false);
    let full = clap_markdown::help_markdown_custom::<super::Cli>(&options);
    // Drop the title and boilerplate paragraph; the book chapter provides its
    // own heading and introduction.
    match full.find("**Command Overview:**") {
        Some(i) => full[i..].to_string(),
        None => full,
    }
}

fn config_markdown() -> eyre::Result<String> {
    let root = serde_json::to_value(crate::schema())?;
    let defs = root.get("$defs").cloned().unwrap_or(Value::Null);
    let mut out = String::new();
    walk_properties(&mut out, &root, &defs, 0);
    Ok(out)
}

/// Emit one bullet per property of `node`, recursing into nested tables.
fn walk_properties(out: &mut String, node: &Value, defs: &Value, depth: usize) {
    let Some(properties) = node.get("properties").and_then(Value::as_object) else {
        return;
    };
    let required: Vec<&str> = node
        .get("required")
        .and_then(Value::as_array)
        .map(|a| a.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();

    for (name, prop) in properties {
        let (resolved, ref_name) = resolve(prop, defs);

        // A map with arbitrary keys, like `projects`: document it as
        // `name.<name>` and descend into the value's schema.
        let pattern_value = resolved
            .get("patternProperties")
            .and_then(Value::as_object)
            .and_then(|p| p.values().next());
        let (display, target, ref_name) = match pattern_value {
            Some(value) => {
                let (target, ref_name) = resolve(value, defs);
                (format!("{name}.<name>"), target, ref_name)
            }
            None => (name.clone(), resolved, ref_name),
        };

        let description = prop
            .get("description")
            .or_else(|| target.get("description"))
            .and_then(Value::as_str)
            .unwrap_or_default();

        let mut meta = vec![type_of(target)];
        if required.contains(&name.as_str()) {
            meta.push("required".to_string());
        }
        let default = match prop.get("default").or_else(|| target.get("default")) {
            Some(d) if !d.is_null() && !d.is_object() => format!(" [default: `{d}`]"),
            _ => String::new(),
        };

        let indent = "  ".repeat(depth);
        let meta = meta.join(", ");
        let description = description.split_whitespace().collect::<Vec<_>>().join(" ");
        out.push_str(&format!(
            "{indent}* `{display}` ({meta}){default} — {description}\n"
        ));

        // The devcontainer schema is documented by its own spec; don't inline
        // its hundreds of options here.
        if ref_name != Some("DevcontainerConfig") {
            walk_properties(out, target, defs, depth + 1);
        }
    }
}

/// Follow `$ref`s and `anyOf [X, null]` wrappers to the real schema, returning
/// it along with the `$defs` name it came from, if any.
fn resolve<'a>(node: &'a Value, defs: &'a Value) -> (&'a Value, Option<&'a str>) {
    if let Some(name) = node
        .get("$ref")
        .and_then(Value::as_str)
        .and_then(|r| r.strip_prefix("#/$defs/"))
        && let Some(def) = defs.get(name)
    {
        return (def, Some(name));
    }
    if let Some(any) = node.get("anyOf").and_then(Value::as_array) {
        let mut non_null = any
            .iter()
            .filter(|v| v.get("type").and_then(Value::as_str) != Some("null"));
        if let (Some(only), None) = (non_null.next(), non_null.next()) {
            return resolve(only, defs);
        }
    }
    (node, None)
}

fn type_of(node: &Value) -> String {
    if node.get("properties").is_some() || node.get("patternProperties").is_some() {
        return "table".to_string();
    }
    match node.get("type") {
        Some(Value::String(s)) => s.clone(),
        Some(Value::Array(a)) => a
            .iter()
            .filter_map(Value::as_str)
            .filter(|s| *s != "null")
            .collect::<Vec<_>>()
            .join(" | "),
        _ => "value".to_string(),
    }
}
